SWP391-Team5/src/java/model/Mentee.java
package model;

public class Mentee {
    //mentee_id, name, account, avatar,gender, status, sum of hours, 
    // sum of skills: get from skill model 
    // sum of mentee: calculate mentee

    //attribute
    private int mentee_id;
    private String mentee_name;
    private String mentee_account;
    private String mentee_avatar_img;
    private byte mentee_gender;
    private byte mentee_status;
    private int mentee_hours;
    private String[] mentee_skill;
    private int time_study;
    private int total_skill;
    
    public Mentee() {
    }

    public Mentee(int mentee_id, String mentee_name, String mentee_account, int time_study, int total_skill) {
        this.mentee_id = mentee_id;
        this.mentee_name = mentee_name;
        this.mentee_account = mentee_account;
        this.time_study = time_study;
        this.total_skill = total_skill;
    }

          
    public Mentee(int mentee_id, String mentee_name, String mentee_account, String mentee_avatar_img, byte mentee_gender, byte mentee_status, int mentee_hours) {
        this.mentee_id = mentee_id;
        this.mentee_name = mentee_name;
        this.mentee_account = mentee_account;
        this.mentee_avatar_img = mentee_avatar_img;
        this.mentee_gender = mentee_gender;
        this.mentee_status = mentee_status;
        this.mentee_hours = mentee_hours;
    }

    //setter
    public void setMentee_id(int mentee_id) {
        this.mentee_id = mentee_id;
    }

    public void setMentee_name(String mentee_name) {
        this.mentee_name = mentee_name;
    }

    public void setMentee_account(String mentee_account) {
        this.mentee_account = mentee_account;
    }

    public void setMentee_avatar_img(String mentee_avatar_img) {
        this.mentee_avatar_img = mentee_avatar_img;
    }

    public void setMentee_gender(byte mentee_gender) {
        this.mentee_gender = mentee_gender;
    }

    public void setMentee_status(byte mentee_status) {
        this.mentee_status = mentee_status;
    }

    public void setMentee_hours(int mentee_hours) {
        this.mentee_hours = mentee_hours;
    }
    
    //getter
    public int getMentee_id() {
        return mentee_id;
    }

    public String getMentee_name() {
        return mentee_name;
    }

    public String getMentee_account() {
        return mentee_account;
    }

    public String getMentee_avatar_img() {
        return mentee_avatar_img;
    }

    public byte getMentee_gender() {
        return mentee_gender;
    }

    public byte getMentee_status() {
        return mentee_status;
    }

    public int getMentee_hours() {
        return mentee_hours;
    }

    public String[] getMentee_skill() {
        return mentee_skill;
    }

    public void setMentee_skill(String[] mentee_skill) {
        this.mentee_skill = mentee_skill;
    }

    public int getTime_study() {
        return time_study;
    }

    public void setTime_study(int time_study) {
        this.time_study = time_study;
    }

    public int getTotal_skill() {
        return total_skill;
    }

    public void setTotal_skill(int total_skill) {
        this.total_skill = total_skill;
    }
    
    
}

SWP391-Team5/src/java/model/RequestName.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.sql.Timestamp;
import java.util.List;

/**
 *
 * @author damtu
 */
public class RequestName {
    private int request_id;
    private int mentor_id;
    private int mentee_id;
    private String title;
    private String request_content;
    private int time_study;
    private Timestamp time_begin;
    private Timestamp created_date;
    private Timestamp finish_date;
    private int request_status;
    private List<Skill> Skill_name;

    public RequestName() {
    }

    public RequestName(int request_id, int mentor_id, int mentee_id, String title, String request_content, int time_study, Timestamp time_begin, Timestamp created_date, Timestamp finish_date, int request_status) {
        this.request_id = request_id;
        this.mentor_id = mentor_id;
        this.mentee_id = mentee_id;
        this.title = title;
        this.request_content = request_content;
        this.time_study = time_study;
        this.time_begin = time_begin;
        this.created_date = created_date;
        this.finish_date = finish_date;
        this.request_status = request_status;
    }
    
    
    
    public int getRequest_id() {
        return request_id;
    }

    public void setRequest_id(int request_id) {
        this.request_id = request_id;
    }

    public int getMentor_id() {
        return mentor_id;
    }

    public void setMentor_id(int mentor_id) {
        this.mentor_id = mentor_id;
    }

    public int getMentee_id() {
        return mentee_id;
    }

    public void setMentee_id(int mentee_id) {
        this.mentee_id = mentee_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getRequest_content() {
        return request_content;
    }

    public void setRequest_content(String request_content) {
        this.request_content = request_content;
    }

    public int getTime_study() {
        return time_study;
    }

    public void setTime_study(int time_study) {
        this.time_study = time_study;
    }

    public Timestamp getTime_begin() {
        return time_begin;
    }

    public void setTime_begin(Timestamp time_begin) {
        this.time_begin = time_begin;
    }

    public Timestamp getCreated_date() {
        return created_date;
    }

    public void setCreated_date(Timestamp created_date) {
        this.created_date = created_date;
    }

    public Timestamp getFinish_date() {
        return finish_date;
    }

    public void setFinish_date(Timestamp finish_date) {
        this.finish_date = finish_date;
    }

    public int getRequest_status() {
        return request_status;
    }

    public void setRequest_status(int request_status) {
        this.request_status = request_status;
    }

    public List<Skill> getSkill_name() {
        return Skill_name;
    }

    public void setSkill_name(List<Skill> Skill_name) {
        this.Skill_name = Skill_name;
    }
    
}

SWP391-Team5/src/java/controller/mentee/FeedbackSuccessfullController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.mentee;

import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 *
 * @author admin
 */
@WebServlet(name = "FeedbackSuccessfullController", urlPatterns = {"/feedbacksuccess"})
public class FeedbackSuccessfullController extends HttpServlet {

    

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.getRequestDispatcher("/mentee/feedbackSuccessful.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.getRequestDispatcher("/mentee/feedbackSuccessful.jsp").forward(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

SWP391-Team5/src/java/controller/mentee/commentAndRateStartController.java
    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.mentee;

import dao.FeedbackDAO;
import dao.MentorCVDAO;
import dao.SkillDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.util.ArrayList;
import java.util.List;
import model.CV_Mentor;
import model.Feedback;
import model.Skill;
import model.User;

/**
 *
 * @author admin
 */
@WebServlet(name = "commentAndRateStartController", urlPatterns = {"/commentAndRateStart"})
public class commentAndRateStartController extends HttpServlet {
    int mentor_id;
    String [] skillId;
    int size;
    //int requeset_id;
    /**
     * 
     * @param request
     * @param response
     * @throws ServletException
     * @throws IOException 
     */
     @Override
     protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
         
         skillId = request.getParameterValues("skillId");
         size = skillId.length;
         SkillDAO kd = new SkillDAO();
         //requeset_id =Integer.parseInt(request.getParameter("requestId")) ;
         mentor_id = Integer.parseInt(request.getParameter("mentorId")) ;
         List<Skill> skillList = new ArrayList<Skill>();
         for (String st : skillId) {
             Skill e = kd.getSkillById(st);
             skillList.add(e);
         }
         request.setAttribute("listSkill", skillList);
         request.getRequestDispatcher("/mentee/feedbackmentor.jsp").forward(request, response);
     }
     
    
    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        // Retrieve rating and opinion from the request
        int rating = Integer.parseInt(request.getParameter("rating")) ;
        String opinion = request.getParameter("opinion");
        
        // Retrieve user_id from the session
        HttpSession session = request.getSession();
        User abc = (User) session.getAttribute("acc");
        int user_id = Integer.parseInt(abc.getUser_id());

        // Retrieve mentor_id from the request
        
        String rating1 = request.getParameter("rating1");
        String rating2 = request.getParameter("rating2");
        String rating3 = request.getParameter("rating3");
        
        int ratingSkill[] = new int[size];
        if(rating1 != null) {
            ratingSkill[0] = Integer.parseInt(rating1);
        } 
        if(rating2 != null) {
            ratingSkill[1] = Integer.parseInt(rating2);
        }
        if(rating3 != null) {
            ratingSkill[2] = Integer.parseInt(rating3);
        }
        FeedbackDAO dao = new FeedbackDAO();
        if(dao.insertFeedbackSkill(user_id, mentor_id, ratingSkill, skillId) == true && dao.insertFeedback(user_id, mentor_id, rating, opinion) == true ) {
            request.getRequestDispatcher("/mentee/feedbackSuccessful.jsp").forward(request, response);
        }else{
            request.setAttribute("error", "Loi roi be oi");
            request.getRequestDispatcher("/mentee/feedbackSuccessful.jsp").forward(request, response);
        }
        
        
        // Insert feedback into the database
//        FeedbackDAO fb = new FeedbackDAO();
//        if (fb.insertFeedback(user_id, mentor_id, rating, opinion)) {
//            // Retrieve CV details of the mentor
//            MentorCVDAO dao = new MentorCVDAO();
//            CV_Mentor cv = dao.getCvMentorById(String.valueOf(mentor_id));
//
//            // Retrieve the list of all mentors
//            List<CV_Mentor> list = dao.getAllListMentor();
//
//            // Retrieve the list of feedback for the mentor
//            FeedbackDAO dao1 = new FeedbackDAO();
//            List<Feedback> listF = dao1.getAllFeedbackOfMentor(mentor_id);
//
//            // Set attributes in the request for further processing
//            request.setAttribute("mentor_id", mentor_id);
//            request.setAttribute("cv", cv);
//            request.setAttribute("listMentor", list);
//            request.setAttribute("listF", listF);
//
//            // Forward the request to the specified JSP file for rendering
//            request.getRequestDispatcher("feedbacksuccess").forward(request, response);
//        }

    }
}

SWP391-Team5/web/mentee/createRequest.jsp
<%-- 
    Document   : createRequest
    Created on : Jun 12, 2023, 9:08:48 PM
    Author     : Tuan Vinh
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<!---Coding By CodingLab | www.codinglabweb.com--->
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />

        <link rel="stylesheet" href="assets/css/request.css" />
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css">
    </head>

    <body>
        <jsp:include page="../home/header.jsp"/>
        <div class="body_temp">
            <section class="container1">    
                <div class="header_title">
                    <div class="header_tmp">
                        <header>Create Request</header>  
                    </div>
                </div>
                <form action="requestMentor" method="post" class="formm">
                    <div class="input-boxx">
                        <label>Title</label>
                        <input type="text" placeholder="Enter the title" name="tieude"required />
                    </div>

                    <div class="columnn">
                        <div class="input-boxx">
                            <label>Start Time</label>
                            <input type="datetime-local" id="start-time" placeholder="Enter start time" name="batdau" required />
                        </div>
                        <div class="input-boxx">
                            <label>End Time</label>
                            <input type="datetime-local" id="end-time" placeholder="Enter end time" name="ketthuc" required />
                        </div>
                    </div>
                    <script>

                        // Lấy thời gian hiện tại
                        var currentTime = new Date();

                        // Thêm 1 giờ vào thời gian hiện tại
                        currentTime.setHours(currentTime.getHours() + 1);

                        // Định dạng chuỗi YYYY-MM-DDTHH:MM
                        var minStartTime = currentTime.toISOString().slice(0, 16);

                        // Thiết lập giá trị tối thiểu cho input thời gian bắt đầu
                        document.getElementById("start-time").setAttribute("min", minStartTime);

                        // Xử lý sự kiện khi giá trị thời gian bắt đầu thay đổi
                        document.getElementById("start-time").addEventListener("input", function () {
                            var startTime = new Date(this.value);

                            // Thêm 1 giờ vào thời gian bắt đầu
                            startTime.setHours(startTime.getHours() + 1);

                            // Định dạng chuỗi YYYY-MM-DDTHH:MM
                            var minEndTime = startTime.toISOString().slice(0, 16);

                            // Thiết lập giá trị tối thiểu cho input thời gian kết thúc
                            document.getElementById("end-time").setAttribute("min", minEndTime);

                            // Kiểm tra điều kiện thời gian và hiển thị thông báo lỗi nếu chọn sai
                            var endTimeInput = document.getElementById("end-time");
                            var endTime = new Date(endTimeInput.value);

                            if (endTime <= startTime) {
                                endTimeInput.setCustomValidity("End time must be greater than start time.");
                            } else {
                                endTimeInput.setCustomValidity(""); // Xóa thông báo lỗi nếu hợp lệ
                            }
                        });
                    </script> 

                    <div class="gender-boxx">
                        <div class="gender-boxx">
                            <label style="font-size: 15px; font-weight: bold;">Skill</label>
                            <div class="gender-option ">
                                <select name="skills" id="skills" multiple=>
                                    <c:forEach items="${listp}" var="o" varStatus="status">
                                        <option value="${o.getSkill_id()}">${o.skill_name}</option>
                                        <c:if test="${status.index % 4 == 3}">
                                            <div style="width: 100%; height: 0;"></div>
                                        </c:if>
                                    </c:forEach>
                                </select>
                            </div>
                        </div>

                    </div>
                    <script>
                        function handleSkillSelection() {
                            var select = document.getElementById("skills");
                            var options = select.selectedOptions;
                            var selectedCount = options.length;
                            var minSelection = 1;
                            var maxSelection = 3;

                            if (selectedCount < minSelection) {
                                alert("Please select at least " + minSelection + " skill.");
                                event.preventDefault(); // Ngăn việc gửi dữ liệu xuống server
                            } else if (selectedCount > maxSelection) {
                                alert("Please select at most " + maxSelection + " skills.");
                                event.preventDefault(); // Ngăn việc gửi dữ liệu xuống server
                            }
                        }
                    </script>

                    <div class="input-boxx">
                        <label>Duration of the request</label>
                        <div class="select-boxx">
                            <select name="sogiohoc" required>
                                <option hidden>Choose time</option>
                                <option value="1">1 hour</option>
                                <option value="2">2 hour</option>
                                <option value="3">3 hour</option>
                                <option value="4">4 hour</option>
                                <option value="5">5 hour</option>
                            </select>
                        </div>
                    </div>
                    <script>
                        // Xử lý sự kiện khi giá trị thay đổi
                        var selectElement = document.querySelector('select[name="sogiohoc"]');
                        selectElement.addEventListener('change', function () {
                            var selectedValue = parseInt(this.value);
                            var startTimeInput = document.getElementById("start-time");
                            var endTimeInput = document.getElementById("end-time");
                            var startTime = new Date(startTimeInput.value);
                            var endTime = new Date(endTimeInput.value);

                            // Thêm số giờ học vào thời gian bắt đầu
                            startTime.setHours(startTime.getHours() + selectedValue);

                            // Kiểm tra điều kiện khoảng cách giữa bắt đầu và kết thúc
                            if (endTime < startTime) {
                                this.setCustomValidity("End time must be greater than or equal to the start time plus duration of the request.");
                            } else {
                                this.setCustomValidity(""); // Xóa thông báo lỗi nếu hợp lệ
                            }
                        });
                    </script>
                    <div class="input-boxx">
                        <label>Content</label><br>
                        <textarea placeholder="Content required" name="noidung" required></textarea>
                    </div>

                    <c:if test="${requestScope.errE!=null}">
                        <h6 style="color: red">${requestScope.errE}</h6>
                    </c:if>
                    <p></p>

                    <button style="border: 30px; background: #175E4C">Request</button>
                </form>
            </section>
        </div>
        <script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/js/multi-select-tag.js"></script>
        <script>
                        new MultiSelectTag('skills')
        </script>

    </body>
    <jsp:include page="../home/footer.jsp"/>
</html>

SWP391-Team5/web/mentee/feedbackSuccessful.jsp
<%-- 
    Document   : forgetPassword
    Created on : Jul 1, 2023, 3:22:04 PM
    Author     : lamnb
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <link rel="icon" href="https://scontent.fhan5-1.fna.fbcdn.net/v/t1.15752-9/346119165_204038079126623_4944693773758350157_n.png?_nc_cat=105&ccb=1-7&_nc_sid=ae9488&_nc_ohc=59rA4Ca5SLQAX9FFAc0&_nc_ht=scontent.fhan5-1.fna&oh=03_AdRxmjNtaFmGhZQ4ul_XUCsH5XiC-mmcQODINzz4E7nZ8A&oe=6496E682">
        <link rel="stylesheet" href="https://cdn.usebootstrap.com/bootstrap/4.2.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="assets/style.min.css" type="text/css" />
        <link rel="stylesheet" href="assets/css/responsive.css" type="text/css" />

        <link rel="stylesheet" href="assets/css/custom.minbc11.css?v=99" type="text/css" />
        <link rel="stylesheet" href="assets/css/override.css" type="text/css" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Successfully</title>
    </head>



    <body class="stretched side-push-panel no-transition">
        <jsp:include page="../home/header.jsp"/>

        <section id="content">
            <div class="content-wrap nopadding" style="margin-top: 109px; min-height: 52vh">
                <div class="login_container"
                     style=" background: url() center center no-repeat; background-size: cover;">
                </div>
                <div class="card card_login divcenter noradius noborder allmargin modal-padding card-login-custom"
                     style="max-width: 500px; background-color: rgba(255,255,255,0.93);">
                    <div class="card-body nopadding">
                        <div class="wrap-title">
                            <h3 class="title">Successfully</h3>
                        </div>
                        <div class="login-logo">
                            <img src="assets/images/logo2.png" alt="ym">
                        </div>
                        <div class="help-block show_err">
                        </div>
                        <div id="change-content">
                            <div class="center">
                            </div>
                            <div class="mb_10 nobottommargin center">
                                <a href="login" class="">Back to home page</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <jsp:include page="../home/footer.jsp"/>
    </body>
</html>

SWP391-Team5/web/mentee/feedbackmentor.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%-- 
    Document   : feedbackmentor
    Created on : Jul 7, 2023, 3:47:22 PM
    Author     : Tuan Vinh
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
        <link rel="icon" href="temp/logo2.png">
        <title>Form Reviews</title>
        <link rel="stylesheet" href="assets/css/feedback1.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    </head>

    <body>
        <jsp:include page="../home/header.jsp"/>
        <div class="containerr">
            <div class="wrapper">
                <form action="commentAndRateStart" method="post">
                    <div
                        style="height: 50px; width: 500px; background-color: #175E4C; margin-bottom: 20px; color: white; border-radius: 6px;">
                        <h1>Feedback For Mentor</h1>
                    </div>
                    <div
                        style="height: 2px; width: 520px; background-color: #175E4C; margin-bottom: 20px; border-radius: 6px;">
                    </div>
                    <h3>Please rate the skills you have learned</h3>
                    <div class="row">

                        <c:forEach begin="0" end="${listSkill.size()-1}" step="1" var="i">
                            <div class="row" style="font-size: 1.5rem">
                                <div class="col-6">
                                    <h3>${listSkill.get(i).skill_name}</h3>
                                </div>
                                <div class="rating${i+1} col-6">
                                    <input type="number" name="rating${i+1}" hidden value="1">
                                    <i class='bx bxs-star star${i+1} active' style="--i: 0;"></i>
                                    <i class='bx bx-star star${i+1}' style="--i: 1;"></i>
                                    <i class='bx bx-star star${i+1}' style="--i: 2;"></i>
                                    <i class='bx bx-star star${i+1}' style="--i: 3;"></i>
                                    <i class='bx bx-star star${i+1}' style="--i: 4;"></i>
                                </div>                               
                            </div>
                        </c:forEach>


                        <!--                    <div class="row">
                                                <div class="col-6">
                                                    <h3>HTML</h3>
                                                </div>
                                                <div class="rating2 col-6">
                                                    <input type="number" name="rating2" hidden>
                                                    <i class='bx bxs-star star2 active' style="--i: 0;"></i>
                                                    <i class='bx bx-star star2' style="--i: 1;"></i>
                                                    <i class='bx bx-star star2' style="--i: 2;"></i>
                                                    <i class='bx bx-star star2' style="--i: 3;"></i>
                                                    <i class='bx bx-star star2' style="--i: 4;"></i>
                                                </div>
                                            </div>
                        
                                            <div class="row">
                                                <div class="col-6">
                                                    <h3>HTML</h3>
                                                </div>
                                                <div class="rating3 col-6">
                                                    <input type="number" name="rating3" hidden>
                                                    <i class='bx bxs-star star3 active' style="--i: 0;"></i>
                                                    <i class='bx bx-star star3' style="--i: 1;"></i>
                                                    <i class='bx bx-star star3' style="--i: 2;"></i>
                                                    <i class='bx bx-star star3' style="--i: 3;"></i>
                                                    <i class='bx bx-star star3' style="--i: 4;"></i>
                                                </div>
                                            </div>-->

                    </div>
                    <div style="margin-top: 20px;">
                        <div
                            style="height: 2px; width: 520px; background-color: #175E4C; margin-bottom: 20px; border-radius: 6px;">
                        </div>
                        <h2>General assessment</h2>

                        <div class="rating" style="font-size: 3rem;">
                            <input type="number" name="rating" hidden value="1">
                            <i class='bx bxs-star star active' style="--i: 0;"></i>
                            <i class='bx bx-star star' style="--i: 1;"></i>
                            <i class='bx bx-star star' style="--i: 2;"></i>
                            <i class='bx bx-star star' style="--i: 3;"></i>
                            <i class='bx bx-star star' style="--i: 4;"></i>
                        </div>
                        <textarea name="opinion" cols="30" rows="5" placeholder="Your opinion..." style="outline: none; resize: none;
                                  " required=""></textarea>
                        <div class="btn-group">
                            <button type="submit" class="btn submit">Submit</button>

                        </div>

                    </div>
                </form>
            </div>
        </div>
        <script src="assets/js/feedback1.js"></script>
        <jsp:include page="../home/footer.jsp"/>
    </body>
</html>

SWP391-Team5/web/mentee/temp.jsp
<%-- 
    Document   : temp
    Created on : Jun 11, 2023, 10:51:52 PM
    Author     : Tuan Vinh
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>